; This file is here for developing esphome-core

[platformio]
env_default = livingroom8266
src_dir = .
include_dir = src

[common]
lib_deps =
    AsyncMqttClient@0.8.2
	bblanchon/ArduinoJson @ ^6.21.5
	ESP32Async/ESPAsyncWebServer @ ^3.6
    https://github.com/ESP32Async/AsyncTCPSock/archive/refs/tags/v1.0.3-dev.zip
lib_ignore =
    AsyncTCP
    ESP32Async/AsyncTCP
build_flags =
    -Wno-reorder
    -DUSE_WEB_SERVER
    -DDONT_STORE_LOG_STR_IN_FLASH
; Don't use FlashStringHelper for debug builds because CLion freaks out for all
; log messages
src_filter = +<src>

[env:livingroom]
platform = espressif32@1.6.0
board = nodemcu-32s
framework = arduino
lib_deps = ${common.lib_deps}
build_flags = ${common.build_flags} -DUSE_ETHERNET
src_filter = ${common.src_filter} +<examples/livingroom/livingroom.cpp>

[env:livingroom8266]
platform = espressif8266@1.8.0
board = nodemcuv2
framework = arduino
lib_deps = ${common.lib_deps}
build_flags = ${common.build_flags} -DESPHOME_LOG_LEVEL=6
src_filter = ${common.src_filter} +<examples/livingroom8266/livingroom8266.cpp>

[env:custombmp180]
platform = espressif8266@1.8.0
board = nodemcuv2
framework = arduino
lib_deps =
    ${common.lib_deps}
    Adafruit BMP085 Library
build_flags = ${common.build_flags}
src_filter = ${common.src_filter} +<examples/custom-bmp180-sensor/custom-bmp180-sensor.cpp>

[env:fastled]
platform = espressif32@1.6.0
board = nodemcu-32s
framework = arduino
lib_deps = ${common.lib_deps}
build_flags = ${common.build_flags}
src_filter = ${common.src_filter} +<examples/fastled/fastled.cpp>
